# =========================
# Database (PostgreSQL)
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/food_delivery
spring.datasource.username=postgres
spring.datasource.password=mohamed4ever
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / Hibernate
# =========================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# SQL Init (schema.sql + data.sql)
# =========================
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql
spring.jpa.defer-datasource-initialization=true

# =========================
# Disable default security
# =========================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
